title: "Jason (Jong Min) Jung"
name: "Jason (Jong Min) Jung"
url: "https://jmjung-dotcom.github.io"
baseurl: ""                  # user site → leave empty

remote_theme: "academicpages/academicpages.github.io"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme      # ← no trailing dot

markdown: kramdown
permalink: /:categories/:title/

# Sidebar / author block
author:
  name: "Jason (Jong Min) Jung"
  avatar: "/images/profile.jpeg"
  bio: "PhD Candidate in Economics, University of Washington"
  location: "Seattle, WA"
  email: "jmjung@uw.edu"

# Social
social:
  - label: "Email"
    icon: "fas fa-envelope"
    url: "mailto:jmjung@uw.edu"
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/jmjung-dotcom"
