title: "Jason (Jong Min) Jung"
name: "Jason (Jong Min) Jung"
url: "https://jmjung-dotcom.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
permalink: /:categories/:title/

author:
  name: "Jason (Jong Min) Jung"
  avatar: "/images/profile.jpeg"
  bio: "PhD Student in Economics, University of Washington"
  location: "Seattle, WA"
  email: "jmjung@uw.edu"

social:
  - label: "Email"
    icon: "fas fa-envelope"
    url: "mailto:jmjung@uw.edu"
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/jmjung-dotcom"

# Custom CSS
minimal_mistakes_skin: default

sass:
  style: compressed

include:
  - assets/css/custom.css
  - _pages

future: true
