title: "Jason (Jong Min) Jung"
name:  "Jason (Jong Min) Jung"

url: "https://jmjung-dotcom.github.io"   # your user/organization page URL
baseurl: ""                               # keep empty for user/organization pages

remote_theme: "academicpages/academicpages.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
permalink: /:categories/:title/

# --- Sidebar / author block ---
author:
  name: "Jason (Jong Min) Jung"
  avatar: "/images/profile.jpeg"     # file exists at images/profile.jpeg
  bio: "PhD Candidate in Economics, University of Washington"
  location: "Seattle, WA"
  email: "jmjung@uw.edu"

# --- Social links (shown under the author card) ---
social:
  - label: "Email"
    icon: "fas fa-envelope"
    url: "mailto:jmjung@uw.edu"
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/jmjung-dotcom"
